const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('rook', {
  send:              (msg)    => ipcRenderer.send('send-to-backend', msg),
  onMessage:         (cb)     => { const h = (_,m) => cb(m); ipcRenderer.on('backend-message', h); return () => ipcRenderer.removeListener('backend-message', h); },
  onPipeStatus:      (cb)     => { const h = (_,s) => cb(s); ipcRenderer.on('pipe-status', h);     return () => ipcRenderer.removeListener('pipe-status', h); },
  onBackendLog:      (cb)     => { const h = (_,l) => cb(l); ipcRenderer.on('backend-log', h);     return () => ipcRenderer.removeListener('backend-log', h); },
  onBackendStart:    (cb)     => { ipcRenderer.once('backend-starting', cb); },
  onAppInit:         (cb)     => { ipcRenderer.once('app-init', (_, d) => cb(d)); },
  onBackendExit:     (cb)     => { const h = (_,d) => cb(d); ipcRenderer.on('backend-exited', h);  return () => ipcRenderer.removeListener('backend-exited', h); },
  onUpdateState:     (cb)     => { const h = (_,s) => cb(s); ipcRenderer.on('update-state', h);    return () => ipcRenderer.removeListener('update-state', h); },
  onTrayNewChat:     (cb)     => { ipcRenderer.on('tray-new-chat', cb); },
  onLoginItemState:  (cb)     => { ipcRenderer.on('login-item-state', (_, v) => cb(v)); },
  reconnectNow:      ()       => ipcRenderer.send('reconnect-now'),
  openExternal:      (url)    => ipcRenderer.invoke('open-external', url),
  browsePlugins:     (opts)   => ipcRenderer.invoke('browse-plugins', opts),
  searchGitHub:      (query)  => ipcRenderer.invoke('github-search', query),
  setGithubToken:    (token)  => ipcRenderer.send('set-github-token', token),
  saveEnvSettings:   (s)      => ipcRenderer.send('save-env-settings', s),
  getPlatformUrl:    ()       => ipcRenderer.invoke('get-platform-url'),
  getPlatformApiKey: ()       => ipcRenderer.invoke('get-platform-api-key'),
  isDevMode:         ()       => ipcRenderer.invoke('is-dev-mode'),
  getAppVersion:     ()       => ipcRenderer.invoke('get-app-version'),
  getUpdateState:    ()       => ipcRenderer.invoke('get-update-state'),
  checkForUpdates:   ()       => ipcRenderer.invoke('check-for-updates'),
  startUpdate:       ()       => ipcRenderer.invoke('start-update'),
  openAuthWindow:    ()       => ipcRenderer.invoke('open-auth-window'),
  onAuthCookie:      (cb)     => { const h = (_,d) => cb(d); ipcRenderer.on('auth-cookie-received', h); return () => ipcRenderer.removeListener('auth-cookie-received', h); },
  onAuthWindowClosed:(cb)     => { ipcRenderer.on('auth-window-closed', cb); },
  showNotification:  (t, b)   => ipcRenderer.send('show-notification', { title: t, body: b }),
  getLoginItem:      ()       => ipcRenderer.invoke('get-login-item'),
  toggleLoginItem:   (enable) => ipcRenderer.send('toggle-login-item', enable),
  readFileDrop:      (fpath)  => ipcRenderer.invoke('read-file-drop', fpath),
  pickFolder:        ()       => ipcRenderer.invoke('pick-folder'),
  minimize:          ()       => ipcRenderer.send('win-minimize'),
  maximize:          ()       => ipcRenderer.send('win-maximize'),
  close:             ()       => ipcRenderer.send('win-close'),
});
